### ISSUE TITLE
AJAX and J! main component view area ?

### ISSUE THREAD

**Issue by pepperstreet** [Joomla-Ajax-Interface/component#26]
Hello, first of all have mercy with my limited knowledge in this area… nonetheless I am interested in this technology from a site-builder's point of view.

Question(s):
**Is there any recommendation or roadmap for AJAX in Joomla's component view?**
**Is this project going to be extended for components?**
**Does it make sense to provide something in J! core, or is it an individual task for every specific extension? Maybe via jQuery features?** 

As far as i understand this repository and feature, it is for modules and plugins, right? But what about the main component area? I could not find any infos in official docs, except for this common resources page:
http://docs.joomla.org/AJAX
Funnily, i found a german Joomla wiki about Mootools & AJAX. But nothing about J!3 and jQuery?!

The only pre-made solution seems to be "Add FullAJAX" on the JED.
http://extensions.joomla.org/extensions/core-enhancements/performance/scripts/13293
Is it an alternative?

So, what might be the future for Joomla! + AJAX?
Thanks for listening.
Maik

**Comment by betweenbrain** [comment]
Hello, and thanks for creating an issue about this. All questions are good!

The short answer is that components have always been able to support AJAX, but never have. Com_ajax extends that possibility to modules and plugins. You can read documentation about com_ajax at http://docs.joomla.org/Using_Joomla_Ajax_Interface, and view a presentation at htttp://matt-thomas.me/talks/ajax-interface.

Currently, there are no pre-built AJAX extensions in core, but I do hope to see some soon. As far as the future, I expect to see this expand, but can never know as someone(s) from the community needs to step forward to do that work. I do hope that com_ajax helps make that happen. I also know that web-services are a major goal of ours, so that may really create a great future for AJAX.

I hope that helps!

**Comment by pepperstreet** [comment]
Hello Matt,
wow, what a fast response… i just have hit the submit button :D ;-)

And yes, that clarifies this project and my first impression. Because this technical stuff is not my main business, it is very hard to get an idea of some theoretical project descriptions. Thanks for pointing me to the presentation link, very kind of you!

best regards,
Maik

**Comment by betweenbrain** [comment]
Hello Mark,

My pleasure! With com_ajax being new, I do expect that interest in this area will increase. Let's hope for the best!

**Comment by wilsonge** [comment]
Yup and I will have a shoutbox module using it as soon as I get the last of the js figured out for it :)
